### ISSUE TITLE
How do I build from source?

### ISSUE THREAD

**Issue by afkvido** [udu3324/Hytools#2]
**Is your feature request related to a problem? Please describe.**
- I would like to know how to build this from source.

**Describe the solution you'd like**
- A guide in the README to build it from source

**Describe alternatives you've considered**
- A guide in the [Wiki](https://github.com/udu3324/Hytools/wiki) to build it from source

**Comment by udu3324** [comment]
Hey, its pretty simple.
1, Clone the repo
2, Extract it into a folder
3, Run "gradlew build" in terminal (make sure you are in the directory of the root project)
4, Go to build/libs and you will see the jar generated.
(note: ignore sources jar as its for devs, not end users)

**Comment by afkvido** [comment]
Thank you very much!
