### ISSUE TITLE
[Bug] Doesn't work on prism launcher

### ISSUE THREAD

**Issue by Aces-and-Jacks** [udu3324/Hytools#24]
### Describe the bug

When I start Minecraft it crashes

### Describe how to replicate bug

1. Install mod
2. crash

### Date of submittion

01/25/2023

### Your java version

Java 8

### Your operating system and the version

MacOS 12.4

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by udu3324** [comment]
Please send your logs

**Comment by afkvido** [comment]
What's prism launcher?

**Comment by Aces-and-Jacks** [comment]
it's a launcher

**Comment by Aces-and-Jacks** [comment]
Maybe the crash also has to do with my operating system but I think it's with the launcher

**Comment by afkvido** [comment]
Took a look. Perhaps there is an issue with mod-to-launcher compatibility, though I've also experienced many Minecraft crashes from mods on MacOS. As udu3324 said, your logs (please remove all tokens and confidential info from them before you send them) are needed to see the cause.

**Comment by afkvido** [comment]
Have you tried this without Prism Launcher?

**Comment by Aces-and-Jacks** [comment]
I haven't tried it without prism launcher. I'll check

**Comment by Aces-and-Jacks** [comment]
ok my mistake. I think I confused this with hycord cause it works now. I'll reopen if it crashes with this mod installed in the future

**Comment by udu3324** [comment]
lol

**Comment by afkvido** [comment]
# 💀

**Comment by Cuteistfox** [comment]
BTW next time you need someone to send logs, tell them to use [mclo.gs](https://mclo.gs/) (use the website or the "Upload" button in prism launcher (ignore the warning in prism launcher)) as it auto redacts stuff (doesnt support JVM crashes yet, but realy you shouldent be sharing a memory dump)

**Comment by Aces-and-Jacks** [comment]
Yeah I normally send in mclo.gs. I don't really know why I didn't post other than me probably not being familiar with the site well enough, or just modding in general.
