### ISSUE TITLE
[FR] Oneconfig

### ISSUE THREAD

**Issue by Cuteistfox** [udu3324/Hytools#42]
### Describe the feature

Use oneconfig for the config.

### Date of submittion

Early autom 25th, 582

### Before submitting a feature request

- [X] This feature wasn't already requested.
(I have checked every feature request on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by udu3324** [comment]
looking at it right now.

**Comment by udu3324** [comment]
progress in https://github.com/udu3324/Hytools/commit/03548ca78fd6f7b7714181daebfa8629a3dc117f

**Comment by udu3324** [comment]
Added in release [1.8](https://github.com/udu3324/Hytools/releases/tag/v1.8).
