### ISSUE TITLE
[FR] Toggle GameRestyle

### ISSUE THREAD

**Issue by afkvido** [udu3324/Hytools#5]
### Describe the feature

I'd like GameRestyle to be returned to Hytools, though this time it should be toggle-able. How about a toggle GameRestyle command, like toggle nick alert Hypixel API?

I like the idea of GameRestyle, but it can be optional for those who don't like it.

### Date of submittion

May 8, 2022

### Before submitting a bug report

- [X] This feature wasn't already requested.
(I have checked every feature request on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by udu3324** [comment]
I cant add it back because of licensing. Sorry.

**Comment by afkvido** [comment]
It's sad, but it's ok.

anyways im exicted for new stuff in Hytools if there's any.


<br>


ty for making this mod tho, it's abseloutly amazing.
