### ISSUE TITLE
[Bug] NickAlert triggers on obfuscated Duel joins

### ISSUE THREAD

**Issue by afkvido** [udu3324/Hytools#7]
### Describe the bug

When joining a duel, NickAlert will ALWAYS say:
```md
####### is nicked!
```
(##### will be some random charecters).

<br><br>

When players join duels, Hypixel sends this:
```md
§k####### joined (#/2)
```
(##### will be some random charecters, # in #/2 will be 1 or 2).

<br><br>

Hytools detects this, and since this random username isn't taken, it sends a NickAlert message, even if **you're** the one joining.

<br>

Hytools Duel NickAlert still works when it tells you your oponent's name, but still, this is a bug.

### Describe how to replicate bug

1. Join a Hypixel duel
2. Hytools tells you that ###### is nicked, for example
```md
9dAjAK2 is nicked!
```

### Date of submittion

May 8, 2022

### Your java version

8 and 17, I have a lot installed

### Your operating system and the version

I tested this on Windows 11, and Mac OS X

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by udu3324** [comment]
should be fixed now

**Comment by afkvido** [comment]
ty!
