### ISSUE TITLE
[FR] Manually set API key/Do not auto-grab API key

### ISSUE THREAD

**Issue by ThatHypedPerson** [udu3324/Hytools#8]
### Describe the feature

Whenever first using this mod it attempts to automatically generate a new API key. This is **_really_** annoying if someone were to have other mods/programs using a Hypixel API key, like myself. Since generating a new API key disabled any previous keys, someone running this program for the first time would have to fix everything else that uses their API key.

In the past when I tried to use this mod it constantly generated a new API key whenever I logged onto the server, so I stopped using it until I tried it again recently. However, when I try it now it constantly fails to grab a new key (probably a bug in itself) due to other mods sending enough commands to cause a "You are sending commands too fast" message. Luckily setting the API key manually in the config file seemed to fix this ~~(I had a whole rant about not being able to set an API key manually before until I figured this out, so uh, yeah i really dislike this mod generating keys itself)~~.

I personally think the best thing to do is add a command to add an API key or tell the user to run `/api new` themselves rather than auto-generate the key for them. Other mods implement API keys this way, and the extra QoL from automatically generating a key does not outweigh the issues it causes.

### Date of submittion

October 18, 2022

### Before submitting a feature request

- [X] This feature wasn't already requested.
(I have checked every feature request on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by udu3324** [comment]
This feature does seem very useful. I will be adding it soon + another command that will disable fetching the API key automatically

**Comment by afkvido** [comment]
_omg it's the issue templates i made!_

**Comment by udu3324** [comment]
Issue closed. 5d78041af9685e32c51d97d60d662bff066f8e2f adds the command & the latest release contains build with it.

Thank you for your suggestion! 
If you have any problems/bugs with the update, lmk lol
